# Jekyll configuration
# Use _config.build.yml to override these settings on `grunt build`.

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

title: "Nigel's Homepage"
url: 'http://localhost:3000'
author: 'Nigel Armstrong'
twitter: 'legonigel'
email: 'nigel@nigelarmstrong.me'
description: 'Nigel Armstrong stuff'

environment: development

exclude: ['img', 'js', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.svg', '**.ico']
keep_files: ['img', 'perf']

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

category_title_prefix: ''
category_dir: /

gems: ['jekyll-paginate']

permalink: /:year/:month/:title/
paginate: 5

# disable this with ''
excerpt_separator: ''

# Use Pygments to highlight code blocks
highlighter: pygments
